### ISSUE TITLE
Feature/Rewrite

### ISSUE THREAD

**Issue by dzove855** [yoctu/yoctapi#2]
The Project should fully rewrite by using yosh new libs.

It should be an Full RESTApi for multiple backend connections, it should explode mysql, redis, beanstalkd , etc... on the web

- Using new api Router : https://github.com/yoctu/yosh/blob/master/lib/api.sh
- Using mapping lib : https://github.com/yoctu/yosh/blob/master/lib/mapping.sh
- Using new meta-gateway, to implement multiple backends and not only mysql: https://github.com/yoctu/libyosh-gateway
- Add query String parameters for rewriting config, like audit, logger, etC...

Everything, should be fully configurable, it should be a 100% generic project. 
We should write new filter and validators, so in the config we can define what should be the validator.

We should use a query constructor, so it is always the same query syntax, instead of writing the query.

**Comment by misterbh** [comment]
add an option to enable of disable logging  for debugging session, useful sometimes

**Comment by dzove855** [comment]
Added.

**Comment by dzove855** [comment]
Done.
